// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_PanelRGB;
extern lv_obj_t * ui_RandomValues;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_ArcValue;
extern lv_obj_t * ui_Value;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_ButtonRGB;
extern lv_obj_t * ui_num32;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_num8;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_num16;
extern lv_obj_t * ui_num4;
extern lv_obj_t * ui_num2;
extern lv_obj_t * ui_num1;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
