// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -45);
    lv_obj_set_y(ui_Label1, 148);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "ESP32-C6 ");

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 29);
    lv_obj_set_height(ui_Panel1, 37);
    lv_obj_set_x(ui_Panel1, -67);
    lv_obj_set_y(ui_Panel1, 82);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0xFF0098), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 29);
    lv_obj_set_height(ui_Panel2, 37);
    lv_obj_set_x(ui_Panel2, -40);
    lv_obj_set_y(ui_Panel2, 82);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xAA00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel2, lv_color_hex(0x6100FF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 29);
    lv_obj_set_height(ui_Panel3, 37);
    lv_obj_set_x(ui_Panel3, -13);
    lv_obj_set_y(ui_Panel3, 82);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x00FFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel3, lv_color_hex(0x00FF65), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 29);
    lv_obj_set_height(ui_Panel4, 37);
    lv_obj_set_x(ui_Panel4, 68);
    lv_obj_set_y(ui_Panel4, 83);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel4, lv_color_hex(0xFFB200), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -13);
    lv_obj_set_y(ui_Label2, 107);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "8");

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 14);
    lv_obj_set_y(ui_Label3, 108);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "4");

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 42);
    lv_obj_set_y(ui_Label4, 108);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "2");

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 68);
    lv_obj_set_y(ui_Label5, 109);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "1");

    ui_PanelRGB = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelRGB, 166);
    lv_obj_set_height(ui_PanelRGB, 50);
    lv_obj_set_x(ui_PanelRGB, 0);
    lv_obj_set_y(ui_PanelRGB, 31);
    lv_obj_set_align(ui_PanelRGB, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelRGB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RandomValues = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RandomValues, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RandomValues, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RandomValues, 0);
    lv_obj_set_y(ui_RandomValues, 30);
    lv_obj_set_align(ui_RandomValues, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RandomValues, "Numbers");
    lv_obj_set_style_bg_color(ui_RandomValues, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RandomValues, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -44);
    lv_obj_set_y(ui_Label7, 131);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "4 MB flash");

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 103);
    lv_obj_set_height(ui_Panel6, -1);
    lv_obj_set_x(ui_Panel6, 76);
    lv_obj_set_y(ui_Panel6, 83);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 33);
    lv_obj_set_height(ui_Spinner1, 35);
    lv_obj_set_x(ui_Spinner1, 68);
    lv_obj_set_y(ui_Spinner1, 143);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xE6FF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ArcValue = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcValue, 112);
    lv_obj_set_height(ui_ArcValue, 110);
    lv_obj_set_x(ui_ArcValue, 3);
    lv_obj_set_y(ui_ArcValue, -49);
    lv_obj_set_align(ui_ArcValue, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcValue, 50);

    lv_obj_set_style_arc_color(ui_ArcValue, lv_color_hex(0x40FFFD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcValue, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcValue, lv_color_hex(0x08F7E1), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcValue, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Value, 1);
    lv_obj_set_y(ui_Value, -50);
    lv_obj_set_align(ui_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Value, "Value");

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -57);
    lv_obj_set_y(ui_Switch1, -144);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_ButtonRGB = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonRGB, 100);
    lv_obj_set_height(ui_ButtonRGB, 28);
    lv_obj_set_x(ui_ButtonRGB, 28);
    lv_obj_set_y(ui_ButtonRGB, -144);
    lv_obj_set_align(ui_ButtonRGB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRGB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRGB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_num32 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_num32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_num32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_num32, -67);
    lv_obj_set_y(ui_num32, 83);
    lv_obj_set_align(ui_num32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_num32, "0");

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 29);
    lv_obj_set_height(ui_Panel7, 37);
    lv_obj_set_x(ui_Panel7, 14);
    lv_obj_set_y(ui_Panel7, 83);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFDF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel7, lv_color_hex(0x8D6E00), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_num8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_num8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_num8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_num8, -13);
    lv_obj_set_y(ui_num8, 83);
    lv_obj_set_align(ui_num8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_num8, "0");

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 29);
    lv_obj_set_height(ui_Panel8, 37);
    lv_obj_set_x(ui_Panel8, 41);
    lv_obj_set_y(ui_Panel8, 83);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x00FF86), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel8, lv_color_hex(0x007509), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_num16 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_num16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_num16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_num16, -41);
    lv_obj_set_y(ui_num16, 83);
    lv_obj_set_align(ui_num16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_num16, "0");

    ui_num4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_num4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_num4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_num4, 14);
    lv_obj_set_y(ui_num4, 83);
    lv_obj_set_align(ui_num4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_num4, "0");

    ui_num2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_num2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_num2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_num2, 41);
    lv_obj_set_y(ui_num2, 84);
    lv_obj_set_align(ui_num2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_num2, "0");

    ui_num1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_num1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_num1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_num1, 68);
    lv_obj_set_y(ui_num1, 84);
    lv_obj_set_align(ui_num1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_num1, "0");

    ui_Label16 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -39);
    lv_obj_set_y(ui_Label16, 107);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "16");

    ui_Label17 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -66);
    lv_obj_set_y(ui_Label17, 106);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "32");

    ui_Label18 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, -118);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "RGB - wifi - Bluetooth");

}
